// from https://timezonedb.com/time-zones

export default [
  {code: 'AF',	timezone: 'Afghanistan	Asia/Kabul'},
  {code: 'AL',	timezone: 'Albania	Europe/Tirane'},
  {code: 'DZ',	timezone: 'Algeria	Africa/Algiers'},
  {code: 'AS',	timezone: 'American Samoa	Pacific/Pago_Pago'},
  {code: 'AD',	timezone: 'Andorra	Europe/Andorra'},
  {code: 'AO',	timezone: 'Angola	Africa/Luanda'},
  {code: 'AI',	timezone: 'Anguilla	America/Anguilla'},
  {code: 'AQ',	timezone: 'Antarctica	Antarctica/Casey'},
  {code: 'AQ',	timezone: 'Antarctica	Antarctica/Davis'},
  {code: 'AQ',	timezone: 'Antarctica	Antarctica/DumontDUrville'},
  {code: 'AQ',	timezone: 'Antarctica	Antarctica/Mawson'},
  {code: 'AQ',	timezone: 'Antarctica	Antarctica/McMurdo'},
  {code: 'AQ',	timezone: 'Antarctica	Antarctica/Palmer'},
  {code: 'AQ',	timezone: 'Antarctica	Antarctica/Rothera'},
  {code: 'AQ',	timezone: 'Antarctica	Antarctica/Syowa'},
  {code: 'AQ',	timezone: 'Antarctica	Antarctica/Troll'},
  {code: 'AQ',	timezone: 'Antarctica	Antarctica/Vostok'},
  {code: 'AG',	timezone: 'Antigua and Barbuda	America/Antigua'},
  {code: 'AR',	timezone: 'Argentina	America/Argentina/Buenos_Aires'},
  {code: 'AR',	timezone: 'Argentina	America/Argentina/Catamarca'},
  {code: 'AR',	timezone: 'Argentina	America/Argentina/Cordoba'},
  {code: 'AR',	timezone: 'Argentina	America/Argentina/Jujuy'},
  {code: 'AR',	timezone: 'Argentina	America/Argentina/La_Rioja'},
  {code: 'AR',	timezone: 'Argentina	America/Argentina/Mendoza'},
  {code: 'AR',	timezone: 'Argentina	America/Argentina/Rio_Gallegos'},
  {code: 'AR',	timezone: 'Argentina	America/Argentina/Salta'},
  {code: 'AR',	timezone: 'Argentina	America/Argentina/San_Juan'},
  {code: 'AR',	timezone: 'Argentina	America/Argentina/San_Luis'},
  {code: 'AR',	timezone: 'Argentina	America/Argentina/Tucuman'},
  {code: 'AR',	timezone: 'Argentina	America/Argentina/Ushuaia'},
  {code: 'AM',	timezone: 'Armenia	Asia/Yerevan'},
  {code: 'AW',	timezone: 'Aruba	America/Aruba'},
  {code: 'AU',	timezone: 'Australia	Antarctica/Macquarie'},
  {code: 'AU',	timezone: 'Australia	Australia/Adelaide'},
  {code: 'AU',	timezone: 'Australia	Australia/Brisbane'},
  {code: 'AU',	timezone: 'Australia	Australia/Broken_Hill'},
  {code: 'AU',	timezone: 'Australia	Australia/Darwin'},
  {code: 'AU',	timezone: 'Australia	Australia/Eucla'},
  {code: 'AU',	timezone: 'Australia	Australia/Hobart'},
  {code: 'AU',	timezone: 'Australia	Australia/Lindeman'},
  {code: 'AU',	timezone: 'Australia	Australia/Lord_Howe'},
  {code: 'AU',	timezone: 'Australia	Australia/Melbourne'},
  {code: 'AU',	timezone: 'Australia	Australia/Perth'},
  {code: 'AU',	timezone: 'Australia	Australia/Sydney'},
  {code: 'AT',	timezone: 'Austria	Europe/Vienna'},
  {code: 'AZ',	timezone: 'Azerbaijan	Asia/Baku'},
  {code: 'BS',	timezone: 'Bahamas	America/Nassau'},
  {code: 'BH',	timezone: 'Bahrain	Asia/Bahrain'},
  {code: 'BD',	timezone: 'Bangladesh	Asia/Dhaka'},
  {code: 'BB',	timezone: 'Barbados	America/Barbados'},
  {code: 'BY',	timezone: 'Belarus	Europe/Minsk'},
  {code: 'BE',	timezone: 'Belgium	Europe/Brussels'},
  {code: 'BZ',	timezone: 'Belize	America/Belize'},
  {code: 'BJ',	timezone: 'Benin	Africa/Porto-Novo'},
  {code: 'BM',	timezone: 'Bermuda	Atlantic/Bermuda'},
  {code: 'BT',	timezone: 'Bhutan	Asia/Thimphu'},
  {code: 'BO',	timezone: 'Bolivia, Plurinational State of	America/La_Paz'},
  {code: 'BQ',	timezone: 'Bonaire, Sint Eustatius and Saba	America/Kralendijk'},
  {code: 'BA',	timezone: 'Bosnia and Herzegovina	Europe/Sarajevo'},
  {code: 'BW',	timezone: 'Botswana	Africa/Gaborone'},
  {code: 'BR',	timezone: 'Brazil	America/Araguaina'},
  {code: 'BR',	timezone: 'Brazil	America/Bahia'},
  {code: 'BR',	timezone: 'Brazil	America/Belem'},
  {code: 'BR',	timezone: 'Brazil	America/Boa_Vista'},
  {code: 'BR',	timezone: 'Brazil	America/Campo_Grande'},
  {code: 'BR',	timezone: 'Brazil	America/Cuiaba'},
  {code: 'BR',	timezone: 'Brazil	America/Eirunepe'},
  {code: 'BR',	timezone: 'Brazil	America/Fortaleza'},
  {code: 'BR',	timezone: 'Brazil	America/Maceio'},
  {code: 'BR',	timezone: 'Brazil	America/Manaus'},
  {code: 'BR',	timezone: 'Brazil	America/Noronha'},
  {code: 'BR',	timezone: 'Brazil	America/Porto_Velho'},
  {code: 'BR',	timezone: 'Brazil	America/Recife'},
  {code: 'BR',	timezone: 'Brazil	America/Rio_Branco'},
  {code: 'BR',	timezone: 'Brazil	America/Santarem'},
  {code: 'BR',	timezone: 'Brazil	America/Sao_Paulo'},
  {code: 'IO',	timezone: 'British Indian Ocean Territory	Indian/Chagos'},
  {code: 'BN',	timezone: 'Brunei Darussalam	Asia/Brunei'},
  {code: 'BG',	timezone: 'Bulgaria	Europe/Sofia'},
  {code: 'BF',	timezone: 'Burkina Faso	Africa/Ouagadougo'},
  {code: 'BI',	timezone: 'Burundi	Africa/Bujumbura'},
  {code: 'KH',	timezone: 'Cambodia	Asia/Phnom_Penh'},
  {code: 'CM',	timezone: 'Cameroon	Africa/Douala'},
  {code: 'CA',	timezone: 'Canada	America/Atikokan'},
  {code: 'CA',	timezone: 'Canada	America/Blanc-Sablon'},
  {code: 'CA',	timezone: 'Canada	America/Cambridge_Bay'},
  {code: 'CA',	timezone: 'Canada	America/Creston'},
  {code: 'CA',	timezone: 'Canada	America/Dawson'},
  {code: 'CA',	timezone: 'Canada	America/Dawson_Creek'},
  {code: 'CA',	timezone: 'Canada	America/Edmonton'},
  {code: 'CA',	timezone: 'Canada	America/Fort_Nelson'},
  {code: 'CA',	timezone: 'Canada	America/Glace_Bay'},
  {code: 'CA',	timezone: 'Canada	America/Goose_Bay'},
  {code: 'CA',	timezone: 'Canada	America/Halifax'},
  {code: 'CA',	timezone: 'Canada	America/Inuvik'},
  {code: 'CA',	timezone: 'Canada	America/Iqaluit'},
  {code: 'CA',	timezone: 'Canada	America/Moncton'},
  {code: 'CA',	timezone: 'Canada	America/Rankin_Inlet'},
  {code: 'CA',	timezone: 'Canada	America/Regina'},
  {code: 'CA',	timezone: 'Canada	America/Resolute'},
  {code: 'CA',	timezone: 'Canada	America/St_Johns'},
  {code: 'CA',	timezone: 'Canada	America/Swift_Current'},
  {code: 'CA',	timezone: 'Canada	America/Toronto'},
  {code: 'CA',	timezone: 'Canada	America/Vancouver'},
  {code: 'CA',	timezone: 'Canada	America/Whitehorse'},
  {code: 'CA',	timezone: 'Canada	America/Winnipeg'},
  {code: 'CV',	timezone: 'Cape Verde	Atlantic/Cape_Verde'},
  {code: 'KY',	timezone: 'Cayman Islands	America/Cayman'},
  {code: 'CF',	timezone: 'Central African Republic	Africa/Bangui'},
  {code: 'TD',	timezone: 'Chad	Africa/Ndjamena'},
  {code: 'CL',	timezone: 'Chile	America/Punta_Arenas'},
  {code: 'CL',	timezone: 'Chile	America/Santiago'},
  {code: 'CL',	timezone: 'Chile	Pacific/Easter'},
  {code: 'CN',	timezone: 'China	Asia/Shanghai'},
  {code: 'CN',	timezone: 'China	Asia/Urumqi'},
  {code: 'CX',	timezone: 'Christmas Island	Indian/Christmas'},
  {code: 'CC',	timezone: 'Cocos (Keeling) Islands	Indian/Cocos'},
  {code: 'CO',	timezone: 'Colombia	America/Bogota'},
  {code: 'KM',	timezone: 'Comoros	Indian/Comoro'},
  {code: 'CG',	timezone: 'Congo	Africa/Brazzaville'},
  {code: 'CD',	timezone: 'Congo, the Democratic Republic of the	Africa/Kinshasa'},
  {code: 'CD',	timezone: 'Congo, the Democratic Republic of the	Africa/Lubumbashi'},
  {code: 'CK',	timezone: 'Cook Islands	Pacific/Rarotonga'},
  {code: 'CR',	timezone: 'Costa Rica	America/Costa_Rica'},
  {code: 'HR',	timezone: 'Croatia	Europe/Zagreb'},
  {code: 'CU',	timezone: 'Cuba	America/Havana'},
  {code: 'CW',	timezone: 'Curaçao	America/Curacao'},
  {code: 'CY',	timezone: 'Cyprus	Asia/Famagusta'},
  {code: 'CY',	timezone: 'Cyprus	Asia/Nicosia'},
  {code: 'CZ',	timezone: 'Czech Republic	Europe/Prague'},
  {code: 'CI',	timezone: 'Côte d\'Ivoire	Africa/Abidja'},
  {code: 'DK',	timezone: 'Denmark	Europe/Copenhagen'},
  {code: 'DJ',	timezone: 'Djibouti	Africa/Djibouti'},
  {code: 'DM',	timezone: 'Dominica	America/Dominica'},
  {code: 'DO',	timezone: 'Dominican Republic	America/Santo_Domingo'},
  {code: 'EC',	timezone: 'Ecuador	America/Guayaquil'},
  {code: 'EC',	timezone: 'Ecuador	Pacific/Galapagos'},
  {code: 'EG',	timezone: 'Egypt	Africa/Cairo'},
  {code: 'SV',	timezone: 'El Salvador	America/El_Salvador'},
  {code: 'GQ',	timezone: 'Equatorial Guinea	Africa/Malabo'},
  {code: 'ER',	timezone: 'Eritrea	Africa/Asmara'},
  {code: 'EE',	timezone: 'Estonia	Europe/Tallinn'},
  {code: 'ET',	timezone: 'Ethiopia	Africa/Addis_Ababa'},
  {code: 'FK',	timezone: 'Falkland Islands (Malvinas)	Atlantic/Stanley'},
  {code: 'FO',	timezone: 'Faroe Islands	Atlantic/Faroe'},
  {code: 'FJ',	timezone: 'Fiji	Pacific/Fiji'},
  {code: 'FI',	timezone: 'Finland	Europe/Helsinki'},
  {code: 'FR',	timezone: 'France	Europe/Paris'},
  {code: 'GF',	timezone: 'French Guiana	America/Cayenne'},
  {code: 'PF',	timezone: 'French Polynesia	Pacific/Gambier'},
  {code: 'PF',	timezone: 'French Polynesia	Pacific/Marquesas'},
  {code: 'PF',	timezone: 'French Polynesia	Pacific/Tahiti'},
  {code: 'TF',	timezone: 'French Southern Territories	Indian/Kerguelen'},
  {code: 'GA',	timezone: 'Gabon	Africa/Libreville'},
  {code: 'GM',	timezone: 'Gambia	Africa/Banju'},
  {code: 'GE',	timezone: 'Georgia	Asia/Tbilisi'},
  {code: 'DE',	timezone: 'Germany	Europe/Berlin'},
  {code: 'DE',	timezone: 'Germany	Europe/Busingen'},
  {code: 'GH',	timezone: 'Ghana	Africa/Accr'},
  {code: 'GI',	timezone: 'Gibraltar	Europe/Gibraltar'},
  {code: 'GR',	timezone: 'Greece	Europe/Athens'},
  {code: 'GL',	timezone: 'Greenland	America/Danmarkshav'},
  {code: 'GL',	timezone: 'Greenland	America/Nuuk'},
  {code: 'GL',	timezone: 'Greenland	America/Scoresbysun'},
  {code: 'GL',	timezone: 'Greenland	America/Thule'},
  {code: 'GD',	timezone: 'Grenada	America/Grenada'},
  {code: 'GP',	timezone: 'Guadeloupe	America/Guadeloupe'},
  {code: 'GU',	timezone: 'Guam	Pacific/Guam'},
  {code: 'GT',	timezone: 'Guatemala	America/Guatemala'},
  {code: 'GG',	timezone: 'Guernsey	Europe/Guernsey'},
  {code: 'GN',	timezone: 'Guinea	Africa/Conakr'},
  {code: 'GW',	timezone: 'Guinea-Bissau	Africa/Bissa'},
  {code: 'GY',	timezone: 'Guyana	America/Guyana'},
  {code: 'HT',	timezone: 'Haiti	America/Port-au-Prince'},
  {code: 'VA',	timezone: 'Holy See (Vatican City State)	Europe/Vatican'},
  {code: 'HN',	timezone: 'Honduras	America/Tegucigalpa'},
  {code: 'HK',	timezone: 'Hong Kong	Asia/Hong_Kong'},
  {code: 'HU',	timezone: 'Hungary	Europe/Budapest'},
  {code: 'IS',	timezone: 'Iceland	Atlantic/Reykjavi'},
  {code: 'IN',	timezone: 'India	Asia/Kolkata'},
  {code: 'ID',	timezone: 'Indonesia	Asia/Jakarta'},
  {code: 'ID',	timezone: 'Indonesia	Asia/Jayapura'},
  {code: 'ID',	timezone: 'Indonesia	Asia/Makassar'},
  {code: 'ID',	timezone: 'Indonesia	Asia/Pontianak'},
  {code: 'IR',	timezone: 'Iran, Islamic Republic of	Asia/Tehran'},
  {code: 'IQ',	timezone: 'Iraq	Asia/Baghdad'},
  {code: 'IE',	timezone: 'Ireland	Europe/Dublin'},
  {code: 'IM',	timezone: 'Isle of Man	Europe/Isle_of_Man'},
  {code: 'IL',	timezone: 'Israel	Asia/Jerusalem'},
  {code: 'IT',	timezone: 'Italy	Europe/Rome'},
  {code: 'JM',	timezone: 'Jamaica	America/Jamaica'},
  {code: 'JP',	timezone: 'Japan	Asia/Tokyo'},
  {code: 'JE',	timezone: 'Jersey	Europe/Jersey'},
  {code: 'JO',	timezone: 'Jordan	Asia/Amman'},
  {code: 'KZ',	timezone: 'Kazakhstan	Asia/Almaty'},
  {code: 'KZ',	timezone: 'Kazakhstan	Asia/Aqtau'},
  {code: 'KZ',	timezone: 'Kazakhstan	Asia/Aqtobe'},
  {code: 'KZ',	timezone: 'Kazakhstan	Asia/Atyrau'},
  {code: 'KZ',	timezone: 'Kazakhstan	Asia/Oral'},
  {code: 'KZ',	timezone: 'Kazakhstan	Asia/Qostanay'},
  {code: 'KZ',	timezone: 'Kazakhstan	Asia/Qyzylorda'},
  {code: 'KE',	timezone: 'Kenya	Africa/Nairobi'},
  {code: 'KI',	timezone: 'Kiribati	Pacific/Kanton'},
  {code: 'KI',	timezone: 'Kiribati	Pacific/Kiritimati'},
  {code: 'KI',	timezone: 'Kiribati	Pacific/Tarawa'},
  {code: 'KP',	timezone: 'Korea, Democratic People\'s Republic of	Asia/Pyongyang'},
  {code: 'KR',	timezone: 'Korea, Republic of	Asia/Seoul'},
  {code: 'KW',	timezone: 'Kuwait	Asia/Kuwait'},
  {code: 'KG',	timezone: 'Kyrgyzstan	Asia/Bishkek'},
  {code: 'LA',	timezone: 'Lao People\'s Democratic Republic	Asia/Vientiane'},
  {code: 'LV',	timezone: 'Latvia	Europe/Riga'},
  {code: 'LB',	timezone: 'Lebanon	Asia/Beirut'},
  {code: 'LS',	timezone: 'Lesotho	Africa/Maseru'},
  {code: 'LR',	timezone: 'Liberia	Africa/Monrovi'},
  {code: 'LY',	timezone: 'Libya	Africa/Tripoli'},
  {code: 'LI',	timezone: 'Liechtenstein	Europe/Vaduz'},
  {code: 'LT',	timezone: 'Lithuania	Europe/Vilnius'},
  {code: 'LU',	timezone: 'Luxembourg	Europe/Luxembourg'},
  {code: 'MO',	timezone: 'Macao	Asia/Macau'},
  {code: 'MK',	timezone: 'Macedonia, the Former Yugoslav Republic of	Europe/Skopje'},
  {code: 'MG',	timezone: 'Madagascar	Indian/Antananarivo'},
  {code: 'MW',	timezone: 'Malawi	Africa/Blantyre'},
  {code: 'MY',	timezone: 'Malaysia	Asia/Kuala_Lumpur'},
  {code: 'MY',	timezone: 'Malaysia	Asia/Kuching'},
  {code: 'MV',	timezone: 'Maldives	Indian/Maldives'},
  {code: 'ML',	timezone: 'Mali	Africa/Bamak'},
  {code: 'MT',	timezone: 'Malta	Europe/Malta'},
  {code: 'MH',	timezone: 'Marshall Islands	Pacific/Kwajalein'},
  {code: 'MH',	timezone: 'Marshall Islands	Pacific/Majuro'},
  {code: 'MQ',	timezone: 'Martinique	America/Martinique'},
  {code: 'MR',	timezone: 'Mauritania	Africa/Nouakchot'},
  {code: 'MU',	timezone: 'Mauritius	Indian/Mauritius'},
  {code: 'YT',	timezone: 'Mayotte	Indian/Mayotte'},
  {code: 'MX',	timezone: 'Mexico	America/Bahia_Banderas'},
  {code: 'MX',	timezone: 'Mexico	America/Cancun'},
  {code: 'MX',	timezone: 'Mexico	America/Chihuahua'},
  {code: 'MX',	timezone: 'Mexico	America/Ciudad_Juarez'},
  {code: 'MX',	timezone: 'Mexico	America/Hermosillo'},
  {code: 'MX',	timezone: 'Mexico	America/Matamoros'},
  {code: 'MX',	timezone: 'Mexico	America/Mazatlan'},
  {code: 'MX',	timezone: 'Mexico	America/Merida'},
  {code: 'MX',	timezone: 'Mexico	America/Mexico_City'},
  {code: 'MX',	timezone: 'Mexico	America/Monterrey'},
  {code: 'MX',	timezone: 'Mexico	America/Ojinaga'},
  {code: 'MX',	timezone: 'Mexico	America/Tijuana'},
  {code: 'FM',	timezone: 'Micronesia, Federated States of	Pacific/Chuuk'},
  {code: 'FM',	timezone: 'Micronesia, Federated States of	Pacific/Kosrae'},
  {code: 'FM',	timezone: 'Micronesia, Federated States of	Pacific/Pohnpei'},
  {code: 'MD',	timezone: 'Moldova, Republic of	Europe/Chisinau'},
  {code: 'MC',	timezone: 'Monaco	Europe/Monaco'},
  {code: 'MN',	timezone: 'Mongolia	Asia/Choibalsan'},
  {code: 'MN',	timezone: 'Mongolia	Asia/Hovd'},
  {code: 'MN',	timezone: 'Mongolia	Asia/Ulaanbaatar'},
  {code: 'ME',	timezone: 'Montenegro	Europe/Podgorica'},
  {code: 'MS',	timezone: 'Montserrat	America/Montserrat'},
  {code: 'MA',	timezone: 'Morocco	Africa/Casablanca'},
  {code: 'MA',	timezone: 'Morocco	Africa/El_Aaiun'},
  {code: 'MZ',	timezone: 'Mozambique	Africa/Maputo'},
  {code: 'MM',	timezone: 'Myanmar	Asia/Yangon'},
  {code: 'NA',	timezone: 'Namibia	Africa/Windhoek'},
  {code: 'NR',	timezone: 'Nauru	Pacific/Nauru'},
  {code: 'NP',	timezone: 'Nepal	Asia/Kathmandu'},
  {code: 'NL',	timezone: 'Netherlands	Europe/Amsterdam'},
  {code: 'NC',	timezone: 'New Caledonia	Pacific/Noumea'},
  {code: 'NZ',	timezone: 'New Zealand	Pacific/Auckland'},
  {code: 'NZ',	timezone: 'New Zealand	Pacific/Chatham'},
  {code: 'NI',	timezone: 'Nicaragua	America/Managua'},
  {code: 'NE',	timezone: 'Niger	Africa/Niamey'},
  {code: 'NG',	timezone: 'Nigeria	Africa/Lagos'},
  {code: 'NU',	timezone: 'Niue	Pacific/Niue'},
  {code: 'NF',	timezone: 'Norfolk Island	Pacific/Norfolk'},
  {code: 'MP',	timezone: 'Northern Mariana Islands	Pacific/Saipan'},
  {code: 'NO',	timezone: 'Norway	Europe/Oslo'},
  {code: 'OM',	timezone: 'Oman	Asia/Muscat'},
  {code: 'PK',	timezone: 'Pakistan	Asia/Karachi'},
  {code: 'PW',	timezone: 'Palau	Pacific/Palau'},
  {code: 'PS',	timezone: 'Palestine, State of	Asia/Gaza'},
  {code: 'PS',	timezone: 'Palestine, State of	Asia/Hebron'},
  {code: 'PA',	timezone: 'Panama	America/Panama'},
  {code: 'PG',	timezone: 'Papua New Guinea	Pacific/Bougainville'},
  {code: 'PG',	timezone: 'Papua New Guinea	Pacific/Port_Moresby'},
  {code: 'PY',	timezone: 'Paraguay	America/Asuncion'},
  {code: 'PE',	timezone: 'Peru	America/Lima'},
  {code: 'PH',	timezone: 'Philippines	Asia/Manila'},
  {code: 'PN',	timezone: 'Pitcairn	Pacific/Pitcairn'},
  {code: 'PL',	timezone: 'Poland	Europe/Warsaw'},
  {code: 'PT',	timezone: 'Portugal	Atlantic/Azore'},
  {code: 'PT',	timezone: 'Portugal	Atlantic/Madeira'},
  {code: 'PT',	timezone: 'Portugal	Europe/Lisbon'},
  {code: 'PR',	timezone: 'Puerto Rico	America/Puerto_Rico'},
  {code: 'QA',	timezone: 'Qatar	Asia/Qatar'},
  {code: 'RO',	timezone: 'Romania	Europe/Bucharest'},
  {code: 'RU',	timezone: 'Russian Federation	Asia/Anadyr'},
  {code: 'RU',	timezone: 'Russian Federation	Asia/Barnaul'},
  {code: 'RU',	timezone: 'Russian Federation	Asia/Chita'},
  {code: 'RU',	timezone: 'Russian Federation	Asia/Irkutsk'},
  {code: 'RU',	timezone: 'Russian Federation	Asia/Kamchatka'},
  {code: 'RU',	timezone: 'Russian Federation	Asia/Khandyga'},
  {code: 'RU',	timezone: 'Russian Federation	Asia/Krasnoyarsk'},
  {code: 'RU',	timezone: 'Russian Federation	Asia/Magadan'},
  {code: 'RU',	timezone: 'Russian Federation	Asia/Novokuznetsk'},
  {code: 'RU',	timezone: 'Russian Federation	Asia/Novosibirsk'},
  {code: 'RU',	timezone: 'Russian Federation	Asia/Omsk'},
  {code: 'RU',	timezone: 'Russian Federation	Asia/Sakhalin'},
  {code: 'RU',	timezone: 'Russian Federation	Asia/Srednekolymsk'},
  {code: 'RU',	timezone: 'Russian Federation	Asia/Tomsk'},
  {code: 'RU',	timezone: 'Russian Federation	Asia/Ust-Nera'},
  {code: 'RU',	timezone: 'Russian Federation	Asia/Vladivostok'},
  {code: 'RU',	timezone: 'Russian Federation	Asia/Yakutsk'},
  {code: 'RU',	timezone: 'Russian Federation	Asia/Yekaterinburg'},
  {code: 'RU',	timezone: 'Russian Federation	Europe/Astrakhan'},
  {code: 'RU',	timezone: 'Russian Federation	Europe/Kaliningrad'},
  {code: 'RU',	timezone: 'Russian Federation	Europe/Kirov'},
  {code: 'RU',	timezone: 'Russian Federation	Europe/Moscow'},
  {code: 'RU',	timezone: 'Russian Federation	Europe/Samara'},
  {code: 'RU',	timezone: 'Russian Federation	Europe/Saratov'},
  {code: 'RU',	timezone: 'Russian Federation	Europe/Ulyanovsk'},
  {code: 'RU',	timezone: 'Russian Federation	Europe/Volgograd'},
  {code: 'RW',	timezone: 'Rwanda	Africa/Kigali'},
  {code: 'RE',	timezone: 'Réunion	Indian/Reunion'},
  {code: 'BL',	timezone: 'Saint Barthélemy	America/St_Barthelemy'},
  {code: 'SH',	timezone: 'Saint Helena, Ascension and Tristan da Cunha	Atlantic/St_Helen'},
  {code: 'KN',	timezone: 'Saint Kitts and Nevis	America/St_Kitts'},
  {code: 'LC',	timezone: 'Saint Lucia	America/St_Lucia'},
  {code: 'MF',	timezone: 'Saint Martin (French part)	America/Marigot'},
  {code: 'PM',	timezone: 'Saint Pierre and Miquelon	America/Miquelon'},
  {code: 'VC',	timezone: 'Saint Vincent and the Grenadines	America/St_Vincent'},
  {code: 'WS',	timezone: 'Samoa	Pacific/Apia'},
  {code: 'SM',	timezone: 'San Marino	Europe/San_Marino'},
  {code: 'ST',	timezone: 'Sao Tome and Principe	Africa/Sao_Tom'},
  {code: 'SA',	timezone: 'Saudi Arabia	Asia/Riyadh'},
  {code: 'SN',	timezone: 'Senegal	Africa/Daka'},
  {code: 'RS',	timezone: 'Serbia	Europe/Belgrade'},
  {code: 'SC',	timezone: 'Seychelles	Indian/Mahe'},
  {code: 'SL',	timezone: 'Sierra Leone	Africa/Freetow'},
  {code: 'SG',	timezone: 'Singapore	Asia/Singapore'},
  {code: 'SX',	timezone: 'Sint Maarten ('},
  {code: 'SK',	timezone: 'Slovakia	Europe/Bratislava'},
  {code: 'SI',	timezone: 'Slovenia	Europe/Ljubljana'},
  {code: 'SB',	timezone: 'Solomon Islands	Pacific/Guadalcanal'},
  {code: 'SO',	timezone: 'Somalia	Africa/Mogadishu'},
  {code: 'ZA',	timezone: 'South Africa	Africa/Johannesburg'},
  {code: 'GS',	timezone: 'South Georgia and the South Sandwich Islands	Atlantic/South_Georgia'},
  {code: 'SS',	timezone: 'South Sudan	Africa/Juba'},
  {code: 'ES',	timezone: 'Spain	Africa/Ceuta'},
  {code: 'ES',	timezone: 'Spain	Atlantic/Canary'},
  {code: 'ES',	timezone: 'Spain	Europe/Madrid'},
  {code: 'LK',	timezone: 'Sri Lanka	Asia/Colombo'},
  {code: 'SD',	timezone: 'Sudan	Africa/Khartoum'},
  {code: 'SR',	timezone: 'Suriname	America/Paramaribo'},
  {code: 'SJ',	timezone: 'Svalbard and Jan Mayen	Arctic/Longyearbyen'},
  {code: 'SZ',	timezone: 'Swaziland	Africa/Mbabane'},
  {code: 'SE',	timezone: 'Sweden	Europe/Stockholm'},
  {code: 'CH',	timezone: 'Switzerland	Europe/Zurich'},
  {code: 'SY',	timezone: 'Syrian Arab Republic	Asia/Damascus'},
  {code: 'TW',	timezone: 'Taiwan, Province of China	Asia/Taipei'},
  {code: 'TJ',	timezone: 'Tajikistan	Asia/Dushanbe'},
  {code: 'TZ',	timezone: 'Tanzania, United Republic of	Africa/Dar_es_Salaam'},
  {code: 'TH',	timezone: 'Thailand	Asia/Bangkok'},
  {code: 'TL',	timezone: 'Timor-Leste	Asia/Dili'},
  {code: 'TG',	timezone: 'Togo	Africa/Lom'},
  {code: 'TK',	timezone: 'Tokelau	Pacific/Fakaofo'},
  {code: 'TO',	timezone: 'Tonga	Pacific/Tongatapu'},
  {code: 'TT',	timezone: 'Trinidad and Tobago	America/Port_of_Spain'},
  {code: 'TN',	timezone: 'Tunisia	Africa/Tunis'},
  {code: 'TR',	timezone: 'Turkey	Europe/Istanbul'},
  {code: 'TM',	timezone: 'Turkmenistan	Asia/Ashgabat'},
  {code: 'TC',	timezone: 'Turks and Caicos Islands	America/Grand_Turk'},
  {code: 'TV',	timezone: 'Tuvalu	Pacific/Funafuti'},
  {code: 'UG',	timezone: 'Uganda	Africa/Kampala'},
  {code: 'UA',	timezone: 'Ukraine	Europe/Kyiv'},
  {code: 'UA',	timezone: 'Ukraine	Europe/Simferopol'},
  {code: 'AE',	timezone: 'United Arab Emirates	Asia/Dubai'},
  {code: 'GB',	timezone: 'United Kingdom	Europe/London'},
  {code: 'US',	timezone: 'United States	America/Adak'},
  {code: 'US',	timezone: 'United States	America/Anchorage'},
  {code: 'US',	timezone: 'United States	America/Boise'},
  {code: 'US',	timezone: 'United States	America/Chicago'},
  {code: 'US',	timezone: 'United States	America/Denver'},
  {code: 'US',	timezone: 'United States	America/Detroit'},
  {code: 'US',	timezone: 'United States	America/Indiana/Indianapolis'},
  {code: 'US',	timezone: 'United States	America/Indiana/Knox'},
  {code: 'US',	timezone: 'United States	America/Indiana/Marengo'},
  {code: 'US',	timezone: 'United States	America/Indiana/Petersburg'},
  {code: 'US',	timezone: 'United States	America/Indiana/Tell_City'},
  {code: 'US',	timezone: 'United States	America/Indiana/Vevay'},
  {code: 'US',	timezone: 'United States	America/Indiana/Vincennes'},
  {code: 'US',	timezone: 'United States	America/Indiana/Winamac'},
  {code: 'US',	timezone: 'United States	America/Juneau'},
  {code: 'US',	timezone: 'United States	America/Kentucky/Louisville'},
  {code: 'US',	timezone: 'United States	America/Kentucky/Monticello'},
  {code: 'US',	timezone: 'United States	America/Los_Angeles'},
  {code: 'US',	timezone: 'United States	America/Menominee'},
  {code: 'US',	timezone: 'United States	America/Metlakatla'},
  {code: 'US',	timezone: 'United States	America/New_York'},
  {code: 'US',	timezone: 'United States	America/Nome'},
  {code: 'US',	timezone: 'United States	America/North_Dakota/Beulah'},
  {code: 'US',	timezone: 'United States	America/North_Dakota/Center'},
  {code: 'US',	timezone: 'United States	America/North_Dakota/New_Salem'},
  {code: 'US',	timezone: 'United States	America/Phoenix'},
  {code: 'US',	timezone: 'United States	America/Sitka'},
  {code: 'US',	timezone: 'United States	America/Yakutat'},
  {code: 'US',	timezone: 'United States	Pacific/Honolulu'},
  {code: 'UM',	timezone: 'United States Minor Outlying Islands	Pacific/Midway'},
  {code: 'UM',	timezone: 'United States Minor Outlying Islands	Pacific/Wake'},
  {code: 'UY',	timezone: 'Uruguay	America/Montevideo'},
  {code: 'UZ',	timezone: 'Uzbekistan	Asia/Samarkand'},
  {code: 'UZ',	timezone: 'Uzbekistan	Asia/Tashkent'},
  {code: 'VU',	timezone: 'Vanuatu	Pacific/Efate'},
  {code: 'VE',	timezone: 'Venezuela, Bolivarian Republic of	America/Caracas'},
  {code: 'VN',	timezone: 'Viet Nam	Asia/Ho_Chi_Minh'},
  {code: 'VG',	timezone: 'Virgin Islands, British	America/Tortola'},
  {code: 'VI',	timezone: 'Virgin Islands, U.S.	America/St_Thomas'},
  {code: 'WF',	timezone: 'Wallis and Futuna	Pacific/Wallis'},
  {code: 'YE',	timezone: 'Yemen	Asia/Aden'},
  {code: 'ZM',	timezone: 'Zambia	Africa/Lusaka'},
  {code: 'ZW',	timezone: 'Zimbabwe	Africa/Harare'},
  {code: 'AX',	timezone: 'Åland Islands	Europe/Mariehamn'},
]